# This file contains measurement specific constants for
# calibration_lib.vna_resonator_spectroscopy

big_sweep_start=6e9
big_sweep_stop=7.5e9 # to match the design values

big_sweep_num_pts=10001
big_sweep_num_ave=20
big_sweep_power=[-50,0,2]

local_sweep_num_pts=2001
local_sweep_power=[-50, 0, 51]

# minimal frequency shift, in Hz, between -50 and 0 dBm powers
min_frequency_diff = 50e3

# For each resonator's estimated resonance frequency
# f@P_hi, at high power, and f@P_low at low power, the sweep to perform is in
# the interval [f@P_hi - delta_span, f@P_hi + delta_span]
# from f@0dBm - 3e6 to f@-50dBm + 3e6
# f@0dBm is lower than f@-50dBm: more power -> lower frequency
delta_span = 3e6

# Estimated resonant frequencies (Sandoko 2023, LokeB)

# *** Roughly, the expected frequencies:
# Q16: 3.256 GHz, Q17: 4.063 GHz, Q18: 3.316 GHz (qubit freqs)
# readout 16: 6.33144 GHz, readout 17: 6.98678 GHz, readout 18: 6.68491 GHz
#
# *** You can start with the following design frequencies:
# Q16: 4 GHz, Q17: 4.946 GHz, Q18: 4.174 GHz (qubit freqs)
# readout 16: 6.519 GHz, readout 17: 7.107 GHz, readout 18: 6.803 GHz

# [resonator_design_frequencies] # not used for the moment, but here for reference
# "16" = 6.519e9
# "17" = 7.107e9
# "18" = 6.803e9 # currently not supported due to instrument configuration issues

[resonator_expected_frequencies]
"16" = 6.33144e9
"17" = 6.98678e9
# "18" = 6.68491e9 # currently not supported due to instrument configuration issues
