#
# Default values for pulsed resonator spectroscopy using ZI / Keysight / Labber
#
# Used to populate scenarios created by scenario_scripts.py for jobs
# with name field "pulsed_resonator_spectroscopy". Creating such a job
# with measurement_jobs/measurement_jobs.py allows these values to be
# overridden by the corresponding keys in the job's 'params' field.

num_pts = 201 # mandatory. name: num_pts # 20M/200 points = 1k sweep frequency resolution
num_pts_other_axis = 21 # mandatory. name: num_pts_other_axis # used when another measurement sweep is required, alt name: num_pts_2d_axis ?
qa_avg = 1024 # mandatory. name: qa_avg # previously num_ave, 1024
qa_integration_length = 4096
qa_delay = 1e3
drive_freq_range_type = "Single"
# qubit excitation frequency = "drive_freq" + "drive_if_freq"
# should be replaced by the measured variable
drive_freq = 274.68e6
drive_start_freq = 270e6
drive_stop_freq = 280e6
drive_amp_range_type = "Single"
drive_amp = 20e-3
drive_amp_start = 1e-3 # DW: used?
drive_amp_stop = 200e-3 # DW: used?
drive_duration = 100e-9
drive_power_range_type = "Single"
drive_power = -10 # used in RS-RF Source
drive_start_power = -20
drive_stop_power = 0
drive_if_freq = 4.5e9
drive_if_span_freq = 20e6
drive_output_enabled = 0
drive_pulse_spacing_range_type = "Single" # pulse spacing only used in ramsey
drive_pulse_spacing_start = 100e-9
drive_pulse_spacing_stop = 2e-6
drive_pulse_spacing = 2e-6 # kept as default value
# Doing a frequency sweep around expected resonace freq
readout_freq_range_type = "Start - Stop"
readout_freq = 379.17e6 # config. name: readout_freq # close to expected resonance frequency, :config
readout_start_freq = 5.99e9 # name: readout_start_freq
readout_stop_freq = 6.01e9 # name: readout_stop_freq
readout_resonance_freq = 5.99931e9
readout_amp_range_type = "Single"
readout_amp = 25e-3 # config. name: readout_amp
readout_amp_start = 5e-3 # name: readout_amp_start
readout_amp_stop = 20e-3 # name: readout_amp_stop
readout_duration = 3e-6
readout_sampling_delay = 200e-9
readout_power_range_type = "Single"
readout_power = 10 # config. name: readout_power
readout_power_start = -20
readout_power_stop = 0
sampling_duration = 2e-6
repetition_delay = 1e-6
integration_window_start = 1e-6
integration_window_stop = 3e-6
trace_time = 5e-6
mqpg_smpl_rate = 2.4e9
hdawg_trigger_range_type = "Single"
hdawg_trigger_period_start = 300e-6
hdawg_trigger_period_stop = 600e-6
hdawg_int_trig_period = 300e-6 # aka relaxation_time
hdawg_marker_start_time = 4.9e-6
hdwag_marker_duration = 100e-9

#################################################################################
# About the parameters (needs to be updated):
#
#  _range_type: sweeping direction, valid values: "Start - Stop", "Span", "Single"
#
# "start_freq: Start of sweeping frequency
# "stop_freq": End of sweeping frequency
# "center_freq": Center of sweeping frequency
# "span_freq": Frequency Span value from center_freq
#
# "power_range_type": Power sweeping type
# "power": used when "Single" or "Span" range type is used
# "start_power": Start of sweeping
# "stop_power": End of sweeping
#
# "drive_output_enabled": RF-Source output used to drive qubit. 0=Off, 1=On
# "drive_amp_range_type": Control MQPG drive signal amplitude sweeping type
# "drive_amp": Control MQPG drive signal amplitude, used when "Single" or "Span" range type is used
# "drive_amp_start": Start of amplitude sweeping
# "drive_amp_stop": Stop of amplitude sweeping
# "drive_duration": Control MQPG drive pulse duration
# "drive_if_freq": Control RF-Source frequency
#
# "num_pts": number of points of measurement
#
# "readout_freq": Readout MQPG frequency
# "readout_amp_range_type": Readout MQPG drive signal amplitude sweeping type
# "readout_amp": Readout MQPG drive signal amplitude, used when "Single" or "Span" range type is used
# "readout_duration": Readout MQPG output pulse duration
# "readout_sampling_delay": A delay that depends on the readout path length
#
# "sampling_duration": signal recording duration
# "repetition_delay":
# "qa_integration_length": intregation of samples to have energy value
# "qa_delay": delay just after recording of pulse, to avoid noise in pulse start point
# "qa_avg": number of recording average
# "integration_window_start": Defines start time when a window is used to define integration scope
# "integration_window_stop": Defines stop time .. as above
#
# "trace_time": MPQG constructed signal length in time
# "mqpg_smpl_rate": DAC sample rate
#
# "hdawg_int_trig_period": minimum time to start another control pulse # aka relaxation_time
# "hdawg_marker_start_time": defines start time of Marker output to signal Readout process
# "hdwag_marker_duration": Marker pulse duration
