#
# Default measurement parameters to be used with ZI / Keysight /
# Labber for Rabi calibration
#
# This file contains default values that should override the common
# default value file.
#
# The keys will / may be overridden by the individual TOML files for
# the respective calibration steps.
#
# The keys are alphabetically sorted.
#

drive_amp_range_type = "Start - Stop"
drive_amp_start = 0.001
drive_amp_stop = 0.2

drive_freq = 274680000.0
drive_freq_range_type = "Single"

drive_output_enabled = 1

num_pts = 200

readout_resonance_freq = 5999310000.0
