#
# Default measurement parameters to be used with ZI / Keysight /
# Labber for Ramsey calibration
#
# This file contains default values that should override the common
# default value file.
#
# The keys will / may be overridden by the individual TOML files for
# the respective calibration steps.
#
# The keys are alphabetically sorted.
#

drive_amp = 0.048 # half the pi-pulse amplitude, depends on Rabi result
drive_amp_range_type = "Single"

drive_freq = 273180000.0 # qubit excitation frequency = "drive_freq" + "drive_if_freq"
drive_freq_range_type = "Single"

drive_output_enabled = 1 # output On, exciting the qubit

drive_pulse_spacing_range_type = "Start - Stop"

num_pts = 191 # 100 ns to 2 us, 191 points = 10 ns sweep resolution

readout_resonance_freq = 5999900000.0 # provided from pulsed resonator spectroscopy
