#
# Default measurement parameters to be used with ZI / Keysight /
# Labber for Ramsey calibration
#
# This file contains default values that should override the common
# default value file.
#
# The keys will / may be overridden by the individual TOML files for
# the respective calibration steps.
#

# ------------------------------------------------------------------------------
# Note:
#
# For documentation about parameters for
# pulsed_resonator_spectroscopy, two_tone, Rabi, and Ramsey job below,
# please read
#
# measurement_jobs/important_parameters.txt
# ------------------------------------------------------------------------------

num_pts = 191 # 100 ns to 2 us, 191 points = 10 ns sweep resolution

drive_output_enabled = 1 # output On, exciting the qubit

drive_amp_range_type = "Single"
drive_amp = 0.064 # half the pi-pulse amplitude, = Rabi result / 2

drive_frequency_if_range_type = "Single"
drive_frequency_if=257741592.0 # 100kHz off (q16?)
# qubit excitation frequency = "drive_frequency_if" + "drive_frequency_lo"

drive_pulse_spacing_range_type = "Start - Stop"

# provided from LO part of pulsed resonator spectroscopy:
readout_frequency_lo = 6000000000.0
