#
# Default measurement parameters to be used with ZI / Keysight /
# Labber for Ramsey calibration
#
# This file contains default values that should override the common
# default value file.
#
# The keys will / may be overridden by the individual TOML files for
# the respective calibration steps.
#
# The keys are alphabetically sorted.
#

drive_amp = 0.048
drive_amp_range_type = "Single"

drive_freq = 273180000.0
drive_freq_range_type = "Single"

drive_output_enabled = 1

drive_pulse_spacing_range_type = "Start - Stop"

num_pts = 191

readout_resonance_freq = 5999900000.0
