#
# Default measurement parameters to be used with ZI / Keysight /
# Labber for two-tone spectroscopy.
#
# This file contains default values that should override the common
# default value file.
#
# The keys will / may be overridden by the individual TOML files for
# the respective calibration steps.
#
# The keys are alphabetically sorted.
#

drive_amp = 0.02
drive_amp_range_type = "Single"

drive_freq_range_type = "Start - Stop"
drive_freq_start = 270000000.0
drive_freq_stop = 280000000.0

# RF-Source output used to drive qubit. 0=Off, 1=On
drive_output_enabled = 1 # output On, exciting the qubit

num_pts = 201 # 20M/200 points = 1k sweep frequency resolution

readout_resonance_freq = 5999310000.0 # provided from pulsed resonator spectroscopy
