#
# Default values for VNA resonator spectroscopy using ZI / Keysight / Labber
#
# Used to populate scenarios created by scenario_scripts.py for jobs
# with name field "resonator_spectroscopy", or
# "fit_resonator_spectroscopy". Creating such a job with
# measurement_jobs/measurement_jobs.py allows these values to be
# overridden by the corresponding keys in the job's 'params' field.

f_start = 6.0e9
f_stop = 7.0e9
if_bw = 1e3
num_pts = 10001
# for single power measurement use single element, eg: [0]
# for multiple power sweep use: [p_start, p_stop, n_pts], eg:[-50, 0, 51]
power = [-50, 0, 51]
num_ave = 10

# Parameters
#
# f_start   : (float) start sweep frequency [Hz]
# f_stop    : (float) stop sweep frequency [Hz]
# if_bw   : (float) IF bandwidth setting [Hz]
# num_pts : (int) number of frequency points
# power   : (int) output power of VNA [dBm]
# num_ave : (int) number of averages
