[general_config]
# general static configuration for the backend
name = "name_of_this_backend"
is_active = true
characterized = true
open_pulse = true
simulator = false
version = "2023.06.10"
online_date = "2022-04-13T19:50:31"
num_qubits = 3
num_couplers = 2
num_resonators = 3
description = "some small description of this device/backend"
dt = 1e-9
dtm = 1e-9


[device_config]
# config names for specification of calibration values
# probably not entirely true for everything herein but mostly so
discriminators = [ "lda", "thresholded_acquisition" ]

qubit_ids = [ "q12", "q13", "q14", "q15" ]

# the spacial [x,y] coordinates of the qubits
coordinates = [ [ 0, 0 ], [ 0, 1 ], [ 1, 0 ], [ 1, 1 ]]

meas_map = [ [ 0, 1, 2, 3 ] ]

qubit_parameters = [
  "id",
  "x_position",
  "y_position",
  "xy_drive_line",
  "z_drive_line",
  "frequency",
  "pi_pulse_amplitude",
  "pi_pulse_duration",
  "pulse_type",
  "pulse_sigma",
  "t1_decoherence",
  "t2_decoherence"
]
resonator_parameters = [
  "id",
  "x_position",
  "y_position",
  "readout_line",
  "acq_delay",
  "acq_integration_time",
  "frequency",
  "pulse_delay",
  "pulse_duration",
  "pulse_type",
  "pulse_amplitude"
]

coupler_parameters = [
  "id",
  "x_position",
  "y_position",
  "xy_drive_line",
  "z_drive_line",
  "frequency",
  "pi_pulse_amplitude",
  "pi_pulse_duration",
  "pulse_type",
  "pulse_sigma",
  "t1_decoherence",
  "t2_decoherence"
]

[device_config.coupling_dict]
# map of coupler channel to qubit pair
u0 = ["q12", "q13"]
u1 = ["q12", "q14"]
u2 = ["q14", "q15"]
u3 = ["q12", "q15"]

[device_config.discriminator_parameters]
lda = [
  "coef_0",
  "coef_1",
  "intercept"
]
thresholded_acquisition = [
  "rotation",
  "threshold"
]

# Configuration for Basis gates
[gates.u]
qubits = [ 0 ]
qasm_def = "gate id q { U(0, 0, 0) q; }"
parameters = [ ]

[gates.h]
qubits = [ 0 ]
qasm_def = "gate id q { U(0, 0, 0) q; }"
parameters = [ ]

[gates.x]
qubits = [ 0 ]
qasm_def = "gate id q { U(0, 0, 0) q; }"
parameters = [ ]

# configuration for values that would be calibrated if this were a real device
[simulator_config.units.qubit]
# configs for units
frequency = "Hz"
t1_decoherence = "s"
t2_decoherence = "s"

[simulator_config.units.readout_resonator]
acq_delay = "s"
acq_integration_time = "s"
frequency = "Hz"
pulse_delay = "s"
pulse_duration = "s"

[simulator_config.units.discriminators]
coef_0 = ""
coef_1 = ""
intercept = ""

# qubits
[[simulator_config.qubit]]
frequency = 4_511_480_043.556283
pi_pulse_amplitude = 0.17555712637424228
pi_pulse_duration = 5.6e-8
pulse_sigma = 7e-9
pulse_type = "Gaussian"
t1_decoherence = 0.000034
t2_decoherence = 0.000033
id = "q12"

[[simulator_config.qubit]]
frequency = 4_677_112_343.360253
pi_pulse_amplitude = 0.17535338530538067
pi_pulse_duration = 5.6e-8
pulse_sigma = 7e-9
pulse_type = "Gaussian"
t1_decoherence = 0.000034
t2_decoherence = 0.000033
id = "q13"

[[simulator_config.qubit]]
frequency = 5_770_226_599.80365
pi_pulse_amplitude = 0.17873594718151276
pi_pulse_duration = 5.6e-8
pulse_sigma = 7e-9
pulse_type = "Gaussian"
t1_decoherence = 0.000034
t2_decoherence = 0.000033
id = "q14"

[[simulator_config.qubit]]
frequency = 6_856_217_811.995201
pi_pulse_amplitude = 0.17326197853513559
pi_pulse_duration = 5.6e-8
pulse_sigma = 7e-9
pulse_type = "Gaussian"
t1_decoherence = 0.000034
t2_decoherence = 0.000033
id = "q15"

# readout resonators
[[simulator_config.readout_resonator]]
acq_delay = 5e-8
acq_integration_time = 0.000001
frequency = 7_260_080_000
pulse_delay = 0
pulse_duration = 9e-7
pulse_type = "Square"
pulse_amplitude = 0.1266499392606423
id = "q12"

[[simulator_config.readout_resonator]]
acq_delay = 5e-8
acq_integration_time = 0.000001
frequency = 7_380_000_000
pulse_delay = 0
pulse_duration = 9e-7
pulse_type = "Square"
pulse_amplitude = 0.12660078572926436
id = "q13"

[[simulator_config.readout_resonator]]
acq_delay = 5e-8
acq_integration_time = 0.000001
frequency = 7_502_000_000
pulse_delay = 0
pulse_duration = 9e-7
pulse_type = "Square"
pulse_amplitude = 0.08245560237524203
id = "q14"

[[simulator_config.readout_resonator]]
acq_delay = 5e-8
acq_integration_time = 0.000001
frequency = 7_712_000_000
pulse_delay = 0
pulse_duration = 9e-7
pulse_type = "Square"
pulse_amplitude = 0.04188729430238
id = "q15"

# discriminators
[simulator_config.discriminators.lda.q12]
score = 0.985
intercept = -38.4344477840827
coef_0 = -98_953.87504155144
coef_1 = -114_154.48696231026

[simulator_config.discriminators.lda.q13]
score = 0.987
intercept = -42.05181160328822
coef_0 = -107_941.00358803963
coef_1 = -124_239.32054386326

[simulator_config.discriminators.lda.q14]
score = 0.9905
intercept = -22.684588212281916
coef_0 = -191_087.42493249022
coef_1 = -20_803.06874845618

[simulator_config.discriminators.lda.q15]
score = 0.8735
intercept = -1.933795064413808
coef_0 = -29_474.17108465108
coef_1 = 78_360.1067777809
