[general_config]
name = "system_test"
is_active = true
characterized = true
open_pulse = true
simulator = false
version = "2023.06.10"
online_date = "2022-04-13T19:50:31"
num_qubits = 10
num_couplers = 2
num_resonators = 10
description = "15 qubit device in Loke"
dt = 1e-9
dtm = 1e-9


[device_config]
discriminators = [ "hw_qmfk", "quadratic_discriminator", "linear_discriminator" ]

qubit_ids = [ 'q16','q17','q18','q19','q20','q21','q22','q23','q24','q25']

coupling_map = [ [ 0, 1 ], [ 1, 0 ] ]

meas_map = [ [ 0, 1, 2 ] ]

qubit_parameters = [
  "id",
  "x_position",
  "y_position",
  "xy_drive_line",
  "z_drive_line",
  "frequency",
  "pi_pulse_amplitude",
  "pi_pulse_duration",
  "pulse_type",
  "pulse_sigma",
  "t1_decoherence",
  "t2_decoherence"
]
resonator_parameters = [
  "id",
  "x_position",
  "y_position",
  "readout_line",
  "acq_delay",
  "acq_integration_time",
  "frequency",
  "pulse_delay",
  "pulse_duration",
  "pulse_type",
  "pulse_amplitude"
]

coupler_parameters = [
  "id",
  "x_position",
  "y_position",
  "xy_drive_line",
  "z_drive_line",
  "frequency",
  "pi_pulse_amplitude",
  "pi_pulse_duration",
  "pulse_type",
  "pulse_sigma",
  "t1_decoherence",
  "t2_decoherence"
]

[gates.u]
qubits = [ 0 ]
qasm_def = "gate id q { U(0, 0, 0) q; }"
parameters = [ ]

[gates.h]
qubits = [ 0 ]
qasm_def = "gate id q { U(0, 0, 0) q; }"
parameters = [ ]

[gates.x]
qubits = [ 0 ]
qasm_def = "gate id q { U(0, 0, 0) q; }"
parameters = [ ]
