# This file declares device backend properties that will updated when BCC runs
#
# This file is meant to support the properties provided by the
# measurement routines committed in the code so far. It can be used as
# a template for configuring properties of the actual device at hand.
#
# See load_config.py for information about the load order of layout
# configuration, property templates, and device configuration.


# Some properties (let's say 'foo') are not indexed: they can be put
# under [device.foo]

[device.name]
notes="Descriptive name of the device/sample"


[device.resonator.frequency_shift]
unit = "Hz"
long_name = "VNA big sweep frequency shift"


[device.resonator.resonant_frequency]
unit = "Hz"
long_name = "Resonator resonant frequency"


[device.qubit.excitation_frequency]
unit = "Hz"
long_name = "Qubit excitation frequency"
