[general_config]
name : str
is_active : bool
characterized = true
open_pulse = true
simulator = false
version = "2023.06.10"
online_date = "2022-04-13T19:50:31"
num_qubits = 3
num_couplers = 2
num_resonators = 3
description = "15 qubit device in Loke"
dt = 1e-9
dtm = 1e-9


[device_config]
discriminators = [ "lda", "thresholded_acquisition" ]

qubit_ids = [ "q12", "q13", "q14" ]

coupling_map = [ [ 0, 1 ], [ 1, 0 ], [ 0, 2 ], [ 2, 0 ]  ]

meas_map = [ [ 0, 1, 2 ] ]

qubit_parameters = [
  "id",
  "x_position",
  "y_position",
  "xy_drive_line",
  "z_drive_line",
  "frequency",
  "pi_pulse_amplitude",
  "pi_pulse_duration",
  "pulse_type",
  "pulse_sigma",
  "t1_decoherence",
  "t2_decoherence"
]
resonator_parameters = [
  "id",
  "x_position",
  "y_position",
  "readout_line",
  "acq_delay",
  "acq_integration_time",
  "frequency",
  "pulse_delay",
  "pulse_duration",
  "pulse_type",
  "pulse_amplitude"
]

coupler_parameters = [
  "id",
  "x_position",
  "y_position",
  "xy_drive_line",
  "z_drive_line",
  "frequency",
  "pi_pulse_amplitude",
  "pi_pulse_duration",
  "pulse_type",
  "pulse_sigma",
  "t1_decoherence",
  "t2_decoherence"
]

[device_config.discriminator_parameters]

lda_parameters = [
  "coef_0",
  "coef_1",
  "intercept"
]

thresholded_acquisition_parameters = [
  "rotation",
  "threshold"
]

[gates.u]
qubits = [ 0 ]
qasm_def = "gate id q { U(0, 0, 0) q; }"
parameters = [ ]

[gates.h]
qubits = [ 0 ]
qasm_def = "gate id q { U(0, 0, 0) q; }"
parameters = [ ]

[gates.x]
qubits = [ 0 ]
qasm_def = "gate id q { U(0, 0, 0) q; }"
parameters = [ ]
