# This file declares device backend properties that will updated when BCC runs
#
# This file is meant to serve as examples to illustrate how to write
# these configuration files, as well as for testing purposes. It can
# be used as a template for configuring properties of the actual
# device at hand.
#
# See load_config.py for information about the load order of layout
# configuration, property templates, and device configuration.

# Some properties (let's say 'foo') are not indexed: they can be put
# under [device.foo]

[device.name]
notes="Descriptive name of the device/sample"

[device.noise]
unit = "dimensionless"
long_name = "Total noise level of the sample"
notes = "Dummy example of a non indexed device property"

[device.resonator.frequency_shift]
unit = "Hz"
long_name = "Big sweep frequency shift"
notes = "VNA resonator spectroscopy, big sweep: should be above a threshold for qubit to be considered functional: see measurement specific configuration."

[device.resonator.resonant_frequency]
unit = "Hz"
long_name = "Local sweep resonant frequency"
notes = "VNA resonator spectroscopy: resonant frequency."

[device.qubit.excitation_frequency]
unit = "Hz"
long_name = "Qubit excitation frequency"

[device.qubit.pi_pulse_amplitude]
unit = "V"
long_name = "Rabi pi pulse amplitude"

[device.qubit.t1]
unit = "s"
long_name = "Thermal relaxation time"
